version: '3.9'

networks:
  default:
    name: g1g2-chain

services:
  # todo: should list relaydb as dependency
  consensus:
    init: true
    build:
      context: ../..
      dockerfile: {{.DeploymentChainNameDir}}/Dockerfile
      #    image: ghcr.io/g1g2.xyz/consensus:latest
      #    restart: unless-stopped
      args:
        SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
    #    image: ghcr.io/g1g2.xyz/dev:latest
    container_name: {{.ChainName}}_consensus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./jwtSecret:/jwtSecret
    environment:
      - LISTEN=0.0.0.0:9876
      # propose
      - PROPOSER_PRIV={{.ProposerPriv}}
      - PROPOSE_BENEFICIARY_ADDRESS={{.ProposeBeneficiary}}
      # sync
      - L2_ENGINE_API_RPC_URL={{.L2EngineApiUrl}}
      - L2_JWT_SECRET=/jwtSecret
      # prover
      - PROVER_PRIV={{.ProverPriv}}
      # relay
      - RELAY_L1_PRIV={{.RelayL1Priv}}
      - RELAY_L2_PRIV={{.RelayL2Priv}}
      - L1_BRIDGE={{.L1Bridge}}
      - L2_BRIDGE={{.L2Bridge}}
      - DB_URL={{.RelayDbUrl}}
      # common
      - L1_RPC_URL={{.L1RpcUrl}}
      - L1_WS_URL={{.L1WsUrl}}
      - L2_RPC_URL={{.L2RpcUrl}}
      - L2_WS_URL={{.L2WsUrl}}
      - L1_ROLLUP={{.L1Rollup}}
      - L2_ROLLUP={{.L2Rollup}}
      - L2_CHAIN_ID={{.ChainId}}
      # misc
      - PROVER_RPCD_URL=http://prover-rpcd:8545
      - PARAMS_PATH=
      - CIRCUIT_NAME=dummy
      - DUMMY_PROVER=true
      - L2_NODE_CANDIDATES=
      # p2p sync
      - ENABLE_P2P_SYNC_ONCHAIN_BLOCKS=true
      - P2P_SYNC_TIMEOUT_SECONDS=90
      - ONLY_SYNC_BLOCKS_BY_P2P=false

    tty: true
    command:
      - --enable-propose
      - --enable-prove
      - --enable-relay
      # - --save-chain-status

  consensus_dev:
    profiles:
      - dev
#    build:
#      context: ../..
#      dockerfile: {{.DeploymentChainNameDir}}/Dockerfile_dev
    image: g1g2/g1g2-dev:2023-02-03
    container_name: {{.ChainName}}_consensus_dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../..:/g1g2-consensus
      - ./jwtSecret:/jwtSecret
      - dev-build-cache:/target:overlay
      - ~/.ssh:/root/.ssh
      - ~/.config/gcloud:/root/.config/gcloud
    working_dir: /g1g2-consensus
    entrypoint: /sbin/getty
    command: '-'
    tty: true
    init: true

volumes:
  dev-build-cache:
