FROM debian:bookworm-slim
RUN set -eux; \
  apt-get update; \
  apt-get install -y --no-install-recommends \
  ca-certificates \
  golang \
  make \
  gcc \
  g++ \
  musl-dev \
  protobuf-compiler \
  procps \
  jq \
  curl \
  git \
  xz-utils \
  ;
