version: '3.9'

services:
  l2_node:
    build:
      context: l2_geth
      dockerfile: l2_geth/Dockerfile
    container_name: "{{.ChainName}}_node"
    volumes:
      - data:/data
    ports:
      - {{.L2HttpPort}}:8545
      - {{.L2WsPort}}:8546
      - {{.L2AuthRpcPort}}:8551

  consensus:
    build:
      context: consensus
      dockerfile: consensus/Dockerfile
    container_name: "{{.ChainName}}_consensus"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - data:/data
    environment:
      - LISTEN=0.0.0.0:9876
      # propose
      - PROPOSER_PRIV={{.ProposerPriv}}
      - PROPOSE_BENEFICIARY_ADDRESS={{.ProposeBeneficiary}}
      # sync
      - L2_ENGINE_API_RPC_URL={{.L2EngineApiUrl}}
      - L2_JWT_SECRET=/jwtSecret
      # prover
      - PROVER_PRIV={{.ProverPriv}}
      # relay
      - RELAY_L1_PRIV={{.RelayL1Priv}}
      - RELAY_L2_PRIV={{.RelayL2Priv}}
      - L1_BRIDGE={{.L1Bridge}}
      - L2_BRIDGE={{.L2Bridge}}
      - DB_URL={{.RelayDbUrl}}
      # common
      - L1_RPC_URL={{.L1RpcUrl}}
      - L1_WS_URL={{.L1WsUrl}}
      - L2_RPC_URL={{.L2RpcUrl}}
      - L2_WS_URL={{.L2WsUrl}}
      - L1_ROLLUP={{.L1Rollup}}
      - L2_ROLLUP={{.L2Rollup}}
      - L2_CHAIN_ID={{.ChainId}}
      # misc
      - PROVER_RPCD_URL=http://prover-rpcd:8545
      - PARAMS_PATH=
      - CIRCUIT_NAME=dummy
      - DUMMY_PROVER=true
      - L2_NODE_CANDIDATES=
      # p2p sync
      - ENABLE_P2P_SYNC_ONCHAIN_BLOCKS=true
      - P2P_SYNC_TIMEOUT_SECONDS=90
      - ONLY_SYNC_BLOCKS_BY_P2P=false
    command:
      - --enable-propose
      - --enable-prove
      - --enable-relay
      - --enable-sync

volumes:
  data:
    name: {{.ChainName}}_node_data
