version: '3.9'

services:
  l1_geth:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: l1_geth
    volumes:
      - data:/data
    environment:
      MINER_PRIVATE_KEY: dc4cf1bba6e4f415e5da84faa4d9981120f8cd1c8a5c956480aeae369325a59f
      MINER_ADDRESS: 0x4331e30d6d8201319D80f6FdB063Ca376114F203
    ports:
      - "10545:8545"
      - "10546:8546"
      - "10547:8551"

volumes:
  data:
    name: l1_geth_data
